mainColin: mainColin.o Mesure.o SerieMesures.o
	g++ -o mainColin mainColin.o Mesure.o SerieMesures.o
Mesure.o: Mesure.cpp
	g++ -o Mesure.o -c Mesure.cpp
SerieMesures.o: SerieMesures.cpp
	g++ -o SerieMesures.o -c SerieMesures.cpp
mainColin.o: mainColin.cpp	
	g++ -o mainColin.o -c mainColin.cpp