mainColin: mainColin.o Mesure.o SerieMesures.o Attribut.o
	g++ -o mainColin mainColin.o Mesure.o SerieMesures.o Attribut.o
Mesure.o: Mesure.cpp
	g++ -o Mesure.o -c Mesure.cpp
SerieMesures.o: SerieMesures.cpp
	g++ -o SerieMesures.o -c SerieMesures.cpp
mainColin.o: mainColin.cpp	
	g++ -o mainColin.o -c mainColin.cpp
Attribut.o: Attribut.cpp
	g++ -o Attribut.o -c Attribut.cpp